import { expect, test } from '@playwright/test'
import { installMockApi } from './mock-api'

test('selects, probes and saves Colab explicitly, persists on reload and keeps the coding draft', async ({ page }, testInfo) => {
  const state = await installMockApi(page)
  await page.goto('/problems/vector-addition')
  await expect(page.getByRole('button', { name: '运行样例', exact: true })).toBeEnabled()
  await expect(page.getByRole('link', { name: 'GPU 执行位置：本地 GPU' })).toBeVisible()
  await page.locator('.monaco-editor .view-lines').click()
  await page.keyboard.press('ControlOrMeta+End')
  await page.keyboard.insertText('\n// execution target changes keep this draft')
  await page.getByRole('link', { name: 'GPU 执行位置：本地 GPU' }).click()
  await page.getByRole('radio', { name: /Google Colab/ }).check()
  await expect(page.getByRole('button', { name: '保存设置' })).toBeDisabled()
  await expect(page.getByTestId('active-execution-target')).toHaveText('当前：本地 GPU')
  await page.getByRole('button', { name: 'Triton (Python)', exact: true }).click()
  await page.getByRole('button', { name: '测试连接', exact: true }).click()
  await expect(page.getByText('Colab · Triton (Python)：连接正常')).toBeVisible()
  expect(state.probes).toEqual([{ target: 'colab', language: 'triton_python' }])
  expect(state.executionSettings.target).toBe('local')
  await expect(page.locator('.environment-hero')).toContainText('本地 GPU')
  await page.getByRole('checkbox', { name: /Colab 不使用 Docker/ }).check()
  await page.getByRole('button', { name: '保存设置' }).click()
  await expect(page.getByTestId('active-execution-target')).toHaveText('当前：Colab')
  await expect(page.getByRole('link', { name: 'GPU 执行位置：Colab' })).toBeVisible()
  await expect(page.locator('.environment-hero')).toContainText('Tesla T4 (Colab)')
  await page.screenshot({ path: testInfo.outputPath('execution-settings-colab.png'), fullPage: true, animations: 'disabled' })
  await page.reload()
  await expect(page.getByRole('radio', { name: /Google Colab/ })).toBeChecked()
  await expect(page.getByRole('checkbox')).toBeChecked()
  await expect(page.getByRole('button', { name: '保存设置' })).toBeDisabled()
  await page.getByRole('link', { name: '题目工作台', exact: true }).click()
  await page.getByRole('link', { name: /向量逐元素相加/ }).click()
  await expect(page.getByRole('link', { name: '执行：Colab', exact: true })).toBeVisible()
  await expect(page.getByRole('button', { name: '运行样例', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: '运行样例', exact: true }).click()
  await expect.poll(() => state.submittedJobs.length).toBe(1)
  expect(state.submittedJobs[0].source).toContain('// execution target changes keep this draft')
  // The backend captures the current target. It is not supplied by the browser as a job override.
  expect(state.submittedJobs[0]).not.toHaveProperty('execution_target')
  await expect(page.locator('.output-status')).toHaveText('Colab')
  await page.getByRole('link', { name: 'GPU 执行位置：Colab' }).click()
  await page.getByRole('radio', { name: /本地 GPU/ }).check()
  await page.getByRole('button', { name: '保存设置' }).click()
  await expect(page.getByRole('link', { name: 'GPU 执行位置：本地 GPU' })).toBeVisible()
  expect(state.executionSettings.target).toBe('local')
})

test('keeps a candidate editable after save denial and worker failure', async ({ page }) => {
  const state = await installMockApi(page)
  await page.route('**/api/execution-settings', async (route) => {
    if (route.request().method() !== 'PUT') return route.fallback()
    return route.fulfill({ status: 403, contentType: 'application/json', body: JSON.stringify({ detail: '无权修改执行设置' }) })
  })
  await page.route('**/api/execution-settings/probe', (route) => route.fulfill({ status: 503, contentType: 'application/json', body: JSON.stringify({ detail: 'Worker 未在线，请启动 Worker 后重试' }) }))
  await page.goto('/environment')
  await page.getByRole('radio', { name: /Google Colab/ }).check()
  await page.getByRole('checkbox').check()
  await page.getByRole('button', { name: '保存设置' }).click()
  await expect(page.getByRole('alert')).toHaveText('无权修改执行设置')
  await expect(page.getByRole('button', { name: '保存设置' })).toBeEnabled()
  await expect(page.getByTestId('active-execution-target')).toHaveText('当前：本地 GPU')
  await page.getByRole('radio', { name: /本地 GPU/ }).check()
  await page.getByRole('button', { name: '测试连接', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Worker 未在线')
  await expect(page.getByRole('button', { name: '测试连接', exact: true })).toBeEnabled()
  await page.getByRole('button', { name: 'PyTorch (Python)', exact: true }).click()
  await expect(page.getByRole('alert')).toHaveCount(0)
  expect(state.executionSettings.target).toBe('local')
})

test('discards a delayed probe after switching candidate or language', async ({ page }) => {
  await installMockApi(page)
  let finishProbe: (() => void) | undefined
  await page.route('**/api/execution-settings/probe', async (route) => {
    await new Promise<void>((resolve) => { finishProbe = resolve })
    await route.fulfill({ status: 200, contentType: 'application/json', body: JSON.stringify({ execution_target: 'colab', backend: 'cuda_cpp', healthy: true, gpu_name: 'Stale Colab GPU' }) })
  })
  await page.goto('/environment')
  await page.getByRole('radio', { name: /Google Colab/ }).check()
  await page.getByRole('button', { name: '测试连接', exact: true }).click()
  await expect(page.getByText(/最多约 3 分钟/)).toBeVisible()
  await page.getByRole('radio', { name: /本地 GPU/ }).check()
  await page.getByRole('button', { name: 'PyTorch (Python)', exact: true }).click()
  await expect.poll(() => typeof finishProbe).toBe('function')
  const response = page.waitForResponse('**/api/execution-settings/probe')
  finishProbe?.()
  await response
  await expect(page.getByText('Stale Colab GPU')).toHaveCount(0)
  await expect(page.getByRole('button', { name: '测试连接', exact: true })).toBeEnabled()
  await expect(page.getByTestId('active-execution-target')).toHaveText('当前：本地 GPU')
})

test('keeps settings readable on a narrow screen in both themes', async ({ page }, testInfo) => {
  await page.setViewportSize({ width: 320, height: 740 })
  await installMockApi(page)
  await page.goto('/environment')
  await page.getByRole('radio', { name: /Google Colab/ }).check()
  for (const theme of ['light', 'dark']) {
    if (theme === 'dark') await page.getByRole('button', { name: '切换到深色模式' }).click()
    await expect(page.getByRole('checkbox')).toBeVisible()
    expect(await page.evaluate(() => document.documentElement.scrollWidth - document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
    await page.screenshot({ path: testInfo.outputPath(`execution-settings-${theme}-mobile.png`), fullPage: true, animations: 'disabled' })
  }
})
